### Reusable workflow to download terraform artifact built by `az_tf_plan` and apply the artifact/plan ###
name: "02-ELKStack"
on:
  workflow_dispatch:
jobs:
  deploy-elkstack:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1  # Specify your preferred AWS region

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity
        
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.3
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
          
    
      - name: Terraform plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.3
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
          
      
      - name: Terraform apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.3
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
          args: '-auto-approve'
    

      - name: Install kubectl
        run: |
          sudo apt-get install -y kubectl

      - name: Configure kubectl for AWS EKS
        run: |
          aws eks update-kubeconfig --name module-eks-mYH0d

      - name: Wait for Resources
        run: sleep 30

      - name: Deploy ELK Stack
        run: | 
          cd modules/elk
          kubectl config view
          kubectl apply -f . --validate=false
    
      - name: Verify kubectl configuration
        run: | 
          sleep 30
          kubectl get svc -n elk
